await import("./test-contracts.mjs");
await import("./test-response-formatting.mjs");
await import("./test-content-runtime-url.mjs");
await import("./test-content-response-extraction.mjs");
await import("./test-project-history-filtering.mjs");
await import("./test-project-history-controller.mjs");
await import("./test-project-target.mjs");
await import("./test-conversation-run-options.mjs");
await import("./test-conversation-adapter.mjs");
await import("./test-project-routing-adapter.mjs");
await import("./test-fresh-conversation-url.mjs");
await import("./test-request-controller-conversation-routing.mjs");
await import("./test-request-controller-cancel.mjs");
await import("./test-dom-utils-click.mjs");
await import("./test-model-scoring.mjs");
await import("./test-main-world-capture.mjs");
await import("./test-response-animation.mjs");
await import("./test-conversation-thread.mjs");
await import("./test-sidepanel-layout-css.mjs");
await import("./test-settings.mjs");
await import("./test-request-records.mjs");
await import("./test-automation-session.mjs");
await import("./test-offscreen-frame-policy.mjs");
await import("./test-offscreen-target.mjs");

console.log("All tests passed.");
